"""Pathway 1 configuration: Acute alveolar hotspot immune-pathogen simulation."""

# ---------------------------
# Core episode configuration
# ---------------------------
TIME_HORIZON = 220
SEED = None

# ---------------------------
# Compartment world geometry
# ---------------------------
WORLD_ROWS = 2
WORLD_COLS = 2
COMPARTMENT_SIZE = 10
PASSAGE_BOTTLENECK_WIDTH = 2
SURFACE_PATCH_DENSITY = 0.22

# Derived global grid size used by existing visualization tooling.
GRID_SIZE = WORLD_ROWS * COMPARTMENT_SIZE + (WORLD_ROWS - 1)
N_COMPARTMENTS = WORLD_ROWS * WORLD_COLS

# ---------------------------
# Initial populations
# ---------------------------
INITIAL_BACTERIA_COUNT = 3
INITIAL_MACROPHAGE_COUNT = 1
MAX_NEUTROPHIL_POOL = 12

# ---------------------------
# Macrophage model
# ---------------------------
MACROPHAGE_MAX_HEALTH = 140
MACROPHAGE_BASE_KILL_DAMAGE = 16
MACROPHAGE_ATTACK_RADIUS = 1
MACROPHAGE_SENSE_RADIUS = 6
MACROPHAGE_SIGNAL_STRENGTH = 5.0
MACROPHAGE_SIGNAL_COOLDOWN = 2
MACROPHAGE_SIGNAL_LOW_STRENGTH = 3.0
MACROPHAGE_SIGNAL_MEDIUM_STRENGTH = 5.0
MACROPHAGE_SIGNAL_HIGH_STRENGTH = 8.0
MACROPHAGE_SIGNAL_LOW_COST = 0.5
MACROPHAGE_SIGNAL_MEDIUM_COST = 1.0
MACROPHAGE_SIGNAL_HIGH_COST = 1.6
MACROPHAGE_SIGNAL_TRIGGER_RADIUS = 6
MACROPHAGE_SIGNAL_LOCAL_CHEMOKINE_THRESHOLD = 1.25
MACROPHAGE_CHEM_SENSE_SCALE = 0.5
MACROPHAGE_HOLD_LOCAL_CHEMOKINE_THRESHOLD = 0.4
HEURISTIC_SIGNAL_PRESSURE_MEDIUM = 3
HEURISTIC_SIGNAL_PRESSURE_HIGH = 5
HEURISTIC_SIGNAL_PRESSURE_LOW = 2
HEURISTIC_SIGNAL_PROXIMITY_RADIUS = 2

# Compatibility alias for older code paths.
MACROPHAGE_HEALTH = MACROPHAGE_MAX_HEALTH

# ---------------------------
# Bacteria model
# ---------------------------
BACTERIA_MAX_HEALTH = 24
BACTERIA_INITIAL_HEALTH = 14
BACTERIA_MATURITY_AGE = 3
BACTERIA_ATTACK_DAMAGE = 5
BACTERIA_ATTACK_PROB = 0.25
BACTERIA_SENSE_RADIUS_MACROPHAGE = 4
BACTERIA_SENSE_RADIUS_NUTRIENT = 4
BACTERIA_ALARM_CHEMOKINE_RELEASE = 0.18

# State transition and biofilm trade-offs.
ATTACHMENT_TIME_REQUIRED = 2
BIOFILM_BUILD_TIME = 3
BIOFILM_DEFENSE_MULTIPLIER = 0.55
BIOFILM_MOTILITY_PENALTY = True
BIOFILM_REPLICATION_MODIFIER = 0.75
BIOFILM_DISPERSAL_DELAY = 2

# ---------------------------
# Resource and replication model
# ---------------------------
PATCH_NUTRIENT_CAPACITY = 14.0
PATCH_REGEN_RATE = 0.2
REPLICATION_REQUIRES_ATTACHMENT = True
REPLICATION_REQUIRES_MIN_PATCH_RESOURCE = 4.0
LOCAL_CARRYING_CAPACITY = 4
BASE_REPLICATION_PROB = 0.35
IMMUNE_PRESSURE_REPLICATION_PENALTY = 0.22

# ---------------------------
# Chemokine and recruitment
# ---------------------------
CHEMOKINE_RELEASE_PER_CONTACT = 2.5
CHEMOKINE_DECAY = 0.9
CHEMOKINE_DIFFUSION_RATE = 0.06
CHEMOKINE_GRADIENT_NOISE = 0.03
NEUTROPHIL_RECRUITMENT_THRESHOLD = 8.0
NEUTROPHIL_ARRIVAL_DELAY = 7
NEUTROPHIL_ARRIVAL_DELAY_JITTER = 2
NEUTROPHIL_MAX_QUEUE_PER_STEP = 3
NEUTROPHIL_BURDEN_EMA = 0.2
NEUTROPHIL_SENSE_RADIUS = 7
NEUTROPHIL_KILL_DAMAGE = 22
NEUTROPHIL_LIFESPAN = 18
NEUTROPHIL_CROWDING_RADIUS = 1
NEUTROPHIL_CROWDING_PENALTY = 0.6
NEUTROPHIL_DOORWAY_BONUS = 0.4
NEUTROPHIL_RECENT_VISIT_MEMORY = 6
NEUTROPHIL_RECENT_VISIT_PENALTY = 0.35

# ---------------------------
# Tissue damage and utility
# ---------------------------
TISSUE_DAMAGE_FROM_NEUTROPHILS = 0.45
TISSUE_DAMAGE_FROM_BACTERIA = 0.1
DAMAGE_FROM_PROLONGED_INFLAMMATION = 0.05
TISSUE_DAMAGE_FAIL_THRESHOLD = 180.0

HOST_UTILITY_ALPHA = 1.0
HOST_UTILITY_BETA = 0.35

# ---------------------------
# Bacteria strategy controls
# ---------------------------
BACTERIA_ADAPTIVE_ENABLED = True
BACTERIA_STOCHASTICITY = 0.12
BACTERIA_MODE = "adaptive"

# ---------------------------
# Planning/search
# ---------------------------
ROLLOUT_BUDGET = 40
MCTS_SIM_DEPTH = 12

# ---------------------------
# RL interface settings
# ---------------------------
RL_PARTIAL_OBS_RADIUS = MACROPHAGE_SENSE_RADIUS
RL_INCLUDE_BELIEF_FEATURES = True
RL_INVALID_ACTION_PENALTY = 1.0
RL_QUEUE_GROWTH_BONUS = 0.0
RL_RECRUITMENT_BONUS = 0.0
RL_VISIBLE_ATTACK_BONUS = 0.8
RL_KILL_BONUS = 1.6
RL_CLOSE_ENGAGEMENT_BONUS = 0.5
RL_APPROACH_VISIBLE_BACTERIA_BONUS = 0.35
RL_RETREAT_FROM_VISIBLE_BACTERIA_PENALTY = 0.45
RL_VISIBLE_BACTERIA_DEFER_PENALTY = 0.5
RL_MISSED_ADJACENT_ATTACK_PENALTY = 1.0
RL_BLIND_SIGNAL_PENALTY = 0.9
RL_SIGNAL_WHILE_VISIBLE_BACTERIA_PENALTY = 0.2
RL_SIGNAL_WHILE_ADJACENT_BACTERIA_PENALTY = 1.0
RL_IDLE_WITHOUT_CUE_PENALTY = 0.15
RL_CONTEXTUAL_SIGNAL_BONUS = 0.85
RL_NEW_TILE_BONUS = 0.04
RL_BACKTRACK_PENALTY = 0.25
RL_DISTANT_SIGNAL_PENALTY = 0.5

# ---------------------------
# Output controls
# ---------------------------
SAVE_PLOTS = True
